# Generated by Django 5.2.3 on 2025-06-20 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetype',
            name='description',
        ),
        migrations.AddField(
            model_name='accused',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accused',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_cognizable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='officer_assigned',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='users.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='name',
            field=models.CharField(choices=[('murder', 'Murder'), ('theft', 'Theft'), ('crime_against_women', 'Crime Against Women'), ('public_nuisance', 'Public Nuisance')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.casetype'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_magistrate', 'Awaiting Magistrate Approval'), ('under_review', 'Under Review'), ('fir_registered', 'FIR Registered'), ('gd_recorded', 'GD Recorded'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
