# Generated by Django 5.2.3 on 2025-06-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_casetype_description_accused_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_number',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
