# Generated by Django 5.2.3 on 2025-06-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='accused',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='incident_location_video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='incident_type_video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='witness',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
