# Generated by Django 5.2.3 on 2025-06-20 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAssignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_at_assignment', models.CharField(max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases_by', to='users.user')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases_to', to='users.user')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='CaseProgress',
            fields=[
                ('progress_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('complaint_registered', 'Complaint Registered'), ('ai_draft_generated', 'AI Draft Generated'), ('assigned_to_officer', 'Assigned to Officer'), ('under_investigation', 'Under Investigation'), ('awaiting_magistrate_approval', 'Awaiting Magistrate Approval'), ('fir_registered', 'FIR Registered'), ('gd_recorded', 'GD Recorded (Non-Cognizable)'), ('closed_resolved', 'Closed/Resolved')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='users.complaint')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('escalation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('escalated_to_role', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='users.complaint')),
                ('escalated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_by', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationUpdate',
            fields=[
                ('update_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_updates', to='users.complaint')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='MagistrateApproval',
            fields=[
                ('approval_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awaiting_approval', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='magistrate_approval', to='users.complaint')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='OfficerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('head_constable', 'Head Constable'), ('sub_inspector', 'Sub-Inspector'), ('sho', 'Station House Officer')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('officer', models.OneToOneField(limit_choices_to={'role': 'officer'}, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
